locale: "en_US"

# Der Rank spieler sollte immer vorhanden sein ansonsten funktioniert das system nicht mehr!
ranks:
  owner:
    prefix: "§4Owner §7• §f"
    players: []
  admin:
    prefix: "§cAdmin §7• §f"
    players: []
  spieler:
    prefix: "§6Player §7• §7"
    players: []