# currently available en_US, de_DE
language: "en_US"

# %p represents the players name
# for a full color pallet open cmd and type 'color ?'
join_message: "&2[&a+&2] &7%p"
leave_message: "&4[&c-&4] &7%p"