name: '${project.artifactId}'
version: '${project.version}'
main: tk.pandadev.nextron.Main
api-version: 1.13
authors: [ PandaDEV ]
description: '${project.description}'
website: '${project.url}'
commands:
  gamemode:
    aliases:
      - gm
      - gms
      - gmc
      - gma
      - gmsp
    permission: nextron.gamemode
  enderchest:
    permission: nextron.enderchest
    aliases:
      - ec
  warp:
    permission: nextron.warp
    aliases:
      - setwarp
      - delwarp
      - renamewarp
      - w
  heal:
    permission: nextron.heal
  vanish:
    permission: nextron.vanish
    aliases:
      - v
  tpa:
    permission: nextron.tpa
  tpaccept:
    permission: nextron.tpaccept
  home:
    permission: nextron.home
    aliases:
      - sethome
      - delhome
      - renamehome
      - h
  invsee:
    permission: nextron.invsee
  tphere:
    permission: nextron.tphere
    aliases:
      - tph
  speed:
    permission: nextron.speed
  fly:
    permission: nextron.fly
  sudo:
    permission: nextron.sudo
  head:
    permission: nextron.head
  rank:
    permission: nextron.rank
    aliases:
      - removerank
      - createrank
      - deleterank
      - modifyrank
  menu:
    aliases:
      - m
  features:
    permission: nextron.features
  back:
    permission: nextron.back
  rename:
    permission: nextron.rename
  help:
  god:
    permission: nextron.god
  day:
    permission: nextron.time
    aliases:
      - night
      - noon
      - midnight
  rl:
    permission: nextron.reload
  tpdeny:
    permission: nextron.tpdeny
    aliases:
      - tpd